project:
  type: website
  output-dir: "docs"

website:
  title: "Matthias Frey"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/matzefrey
      
format:
  html:
    theme: sandstone
    css: styles.css



